#!/bin/bash
# Warn (non-blocking) when an Edit/Write/MultiEdit targets a path that affects
# the published API surface or downstream consumers. Reminds Claude of the
# specific rule from CLAUDE.md that applies to this file.
#
# Exit code: always 0 (advisory). Surfaces a stderr message Claude will read.

set -u

if ! command -v jq >/dev/null 2>&1; then
  exit 0
fi

payload=$(cat)

target=$(jq -r '.tool_input.file_path // empty' <<<"$payload")
[ -z "$target" ] && exit 0

# Text this call is about to write: Write uses .content, Edit uses .new_string,
# MultiEdit carries one .new_string per edit.
written=$(jq -r '[.tool_input.content, .tool_input.new_string, (.tool_input.edits[]?.new_string)] | map(select(. != null)) | join("\n")' <<<"$payload")

# Combined haystack for content checks: an incremental Edit only carries its own
# replacement string, so a light:/dark: pair that arrives in two edits would
# never be seen. Pair the new text with what is already on disk.
haystack="$written"
if [ -f "$target" ]; then
  haystack="$written
$(cat "$target")"
fi

project_dir="${CLAUDE_PROJECT_DIR:-$(pwd)}"
rel="${target#"$project_dir"/}"

warn() {
  cat >&2 <<EOF
NOTE from .claude/hooks/pre-write-warn-public-surface.sh: '$rel'
$1
EOF
}

case "$rel" in
  src/index.ts)
    warn "This file is the PUBLIC API surface re-exported by every consuming dapp.
  • Named exports only — no 'export *' (CLAUDE.md §5; tree-shaking depends on it).
  • Keep MUI re-exports alphabetical within their section.
  • Removing or renaming an export is a breaking change for consumers."
    ;;
  src/types/emotion.ts)
    warn "Emotion theme augmentation. Changing this can silently break consumers'
  styled() typings. Verify with 'npm run build' before committing — CLAUDE.md §6."
    ;;
  src/theme/colors.ts|src/theme/colorSchemes.ts|src/theme/components.ts|src/theme/typography.ts|src/theme/index.ts)
    warn "Design token / theme file. Downstream apps reference these via CSS custom
  properties (var(--mui-palette-…)). Changes propagate at next bump — CLAUDE.md §6.
  Renaming a token without a deprecation path is a breaking change."
    ;;
  package.json)
    warn "Changes to package.json affect every consumer.
  • peerDependencies bumps (@dcl/schemas, @dcl/hooks, react) are BREAKING — coordinate with consuming dapps.
  • New scripts: verify they line up with the pre-PR pipeline order (CLAUDE.md §9).
  • Caret '^' for @dcl/* and decentraland-*; exact pins for everything else (ADR-6, ~/.claude/CLAUDE.md)."
    ;;
  package-lock.json)
    warn "package-lock.json is committed and drives every CI install.
  • Regenerate via 'npm install <pkg>', never hand-edit.
  • Do not run 'npm install --package-lock-only' (the destructive hook blocks it)."
    ;;
  eslint.config.js)
    warn "eslint.config.js extends @dcl/eslint-config/ui.config and currently disables
  three rules with a TODO (CLAUDE.md §12). Do not add to the override block without a
  follow-up PR to fix the underlying violations."
    ;;
  tsconfig.json|.babelrc.json)
    warn "Build/typecheck config. Changes can produce a published 'dist/' that compiles
  locally but breaks consumer types. Run 'npm run build' and inspect dist/index.d.ts after editing."
    ;;
  bin/storybookGenerator.ts|bin/muiComponentConfig.ts|bin/templates.ts)
    warn "Storybook generator. 'npm run generate:storybooks' runs this and WIPES src/@mui/.
  Do not hand-edit anything under src/@mui/ — it is regenerated. CLAUDE.md §12."
    ;;
  src/@mui/*)
    warn "src/@mui/ is auto-generated by bin/storybookGenerator.ts. Hand-edits are
  discarded the next time 'npm run generate:storybooks' runs. Edit the generator instead."
    ;;
  src/components/*)
    # Fires only on a light:/dark: object-literal PAIR, i.e. a per-scheme token
    # store. Deliberately does NOT match a bare 'palette.mode' ternary: that is
    # the incumbent pattern in EventCard / EventSmallCard / SceneCard /
    # CatalogCard, and warning on it would make this hook noise.
    if printf '%s' "$haystack" | grep -qE '(^|[^A-Za-z_])light:[[:space:]]*\{' &&
      printf '%s' "$haystack" | grep -qE '(^|[^A-Za-z_])dark:[[:space:]]*\{'; then
      warn "This edit looks like a per-scheme (light/dark) token store inside a component.
  Design values belong in src/theme/colorSchemes.ts under palette._components.<component>,
  typed in src/types/emotion.ts; the component then reads them off the theme inside styled().
  See CLAUDE.md §6 and the skill .claude/skills/styled-with-mui.
  A local 'const FOO_SCHEMES = { light, dark }' map was rejected in review on PR #472."
    fi
    ;;
esac

exit 0
