export const components = {
  MuiButton: {
    styleOverrides: {
      root: {
        "&.MuiButton-sizeLarge.MuiButton-containedPrimary": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-contrast)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-primary-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-contrast)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedInherit": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedInherit (white)": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-common-white_states-main)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedSecondary": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "8px 22px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-main)",
            boxShadow: "var(--mui-shadows-2)",
            opacity: "1",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "8px 22px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-main)",
            boxShadow: "var(--mui-shadows-6)",
            opacity: "1",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-secondary-secondary-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "8px 22px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-dark)",
            boxShadow: "var(--mui-shadows-4)",
            opacity: "1",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedError": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-contrast)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-error-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-contrast)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedWarning": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-contrast)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-warning-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-contrast)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedInfo": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-contrast)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-info-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-contrast)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-containedSuccess": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-contrast)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-success-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-contrast)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedPrimary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-contrast)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-primary-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-contrast)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedInherit": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedInherit (white)": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-common-white_states-main)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedSecondary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "6px 16px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-main)",
            boxShadow: "var(--mui-shadows-2)",
            opacity: "1",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "6px 16px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-main)",
            boxShadow: "var(--mui-shadows-6)",
            opacity: "1",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-secondary-secondary-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "6px 16px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-dark)",
            boxShadow: "var(--mui-shadows-4)",
            opacity: "1",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedError": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-contrast)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-error-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-contrast)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedWarning": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-contrast)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-warning-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-contrast)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedInfo": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-contrast)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-info-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-contrast)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-containedSuccess": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-contrast)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-success-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-contrast)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedPrimary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-contrast)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-primary-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-contrast)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedInherit": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedInherit (white)": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-common-white_states-main)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedSecondary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "4px 10px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-main)",
            boxShadow: "var(--mui-shadows-2)",
            opacity: "1",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "4px 10px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-main)",
            boxShadow: "var(--mui-shadows-6)",
            opacity: "1",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-secondary-secondary-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-contrast)",
            padding: "4px 10px",
            borderRadius: "var(--mui-shape-borderRadius)",
            background: "var(--mui-palette-secondary-secondary-dark)",
            boxShadow: "var(--mui-shadows-4)",
            opacity: "1",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedError": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-contrast)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-error-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-contrast)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedWarning": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-contrast)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-warning-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-contrast)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedInfo": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-contrast)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-info-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-contrast)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-containedSuccess": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-contrast)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-contrast)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              opacity: "0.3",
              background: "var(--mui-palette-success-contrast)",
              padding: "0",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-contrast)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedPrimary": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedInherit": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedInherit (white)": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-common-white_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedSecondary": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedError": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-error-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedWarning": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-warning-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedInfo": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-outlinedSuccess": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-main)",
            "& .MuiTouchRipple-root": {
              width: "69.209px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-success-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedPrimary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedInherit": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedInherit (white)": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-common-white_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedSecondary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedError": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-error-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedWarning": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-warning-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedInfo": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-outlinedSuccess": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-main)",
            "& .MuiTouchRipple-root": {
              width: "57.429px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-success-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedPrimary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedInherit": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedInherit (white)": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-common-white_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedSecondary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedError": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-error-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedWarning": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-warning-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedInfo": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-main)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-outlinedSuccess": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-main)",
            "& .MuiTouchRipple-root": {
              width: "46.385px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-success-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-main)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textPrimary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textInherit": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textInherit (white)": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-common-white_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textSecondary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textError": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-error-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textWarning": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-warning-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textInfo": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeMedium.MuiButton-textSuccess": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.875rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "24px /* 171.429% */",
          letterSpacing: "0.4px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-main)",
            "& .MuiTouchRipple-root": {
              width: "45.648px",
              height: "46.286px",
              borderRadius: "100px",
              background: "var(--mui-palette-success-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textPrimary": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textInherit": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textInherit (white)": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-common-white_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textSecondary": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textError": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-error-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textWarning": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-warning-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textInfo": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeLarge.MuiButton-textSuccess": {
          fontFeatureSettings: "'clig' off, 'liga' off",
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.9375rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "26px /* 173.333% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-main)",
            "& .MuiTouchRipple-root": {
              width: "53.011px",
              height: "54px",
              borderRadius: "100px",
              background: "var(--mui-palette-success-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textPrimary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
            display: "none",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-primary-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-primary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textInherit": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-text-primary)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-text-primary)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-text-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-text-primary)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textInherit (white)": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-common-white_states-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-common-white_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-common-white_states-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textSecondary": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-secondary-secondary-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-secondary-secondary-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textError": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-error-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-error-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-error-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-error-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textWarning": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-warning-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-warning-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-warning-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-warning-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textInfo": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-info-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-info-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-primary-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-info-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
        "&.MuiButton-sizeSmall.MuiButton-textSuccess": {
          fontFamily: "Inter, Helvetica, Arial, sans-serif",
          fontSize: "0.8125rem",
          fontStyle: "normal",
          fontWeight: "600",
          lineHeight: "22px /* 169.231% */",
          letterSpacing: "0.46px",
          textTransform: "uppercase",
          "&:not(.Mui-disabled):not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-success-main)",
          },
          "&:not(.Mui-disabled).Mui-focusVisible:not(:hover)": {
            color: "var(--mui-palette-success-main)",
            "& .MuiTouchRipple-root": {
              width: "39.022px",
              height: "38.571px",
              borderRadius: "100px",
              background: "var(--mui-palette-success-_states-focusVisible)",
              padding: "0",
              opacity: "1",
              boxShadow: "none",
            },
          },
          "&:not(.Mui-disabled):not(.Mui-focusVisible):hover": {
            color: "var(--mui-palette-success-main)",
          },
          "&.Mui-disabled:not(.Mui-focusVisible):not(:hover)": {
            color: "var(--mui-palette-action-disabled)",
          },
        },
      },
    },
  },
  MuiSwitch: {
    styleOverrides: {
      root: {
        "&.MuiSwitch-sizeMedium:has(.MuiSwitch-colorSecondary)": {
          "& .MuiSwitch-switchBase": {
            "& .MuiSwitch-thumb": {
              width: "20px",
              height: "20px",
              background: "var(--mui-palette-secondary-secondary-main)",
              boxShadow: "var(--mui-shadows-1)",
              padding: "0",
              opacity: "1",
              borderRadius: "50%",
            },
            "& + .MuiSwitch-track": {
              width: "34px",
              height: "14px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-secondary-main)",
              padding: "0",
              boxShadow: "none",
            },
          },
        },
        "&.MuiSwitch-sizeSmall:has(.MuiSwitch-colorSecondary)": {
          "& .MuiSwitch-switchBase": {
            "& .MuiSwitch-thumb": {
              width: "16px",
              height: "16px",
              background: "var(--mui-palette-secondary-secondary-main)",
              boxShadow: "var(--mui-shadows-1)",
              padding: "0",
              opacity: "1",
              borderRadius: "50%",
            },
            "& + .MuiSwitch-track": {
              width: "26px",
              height: "10px",
              borderRadius: "100px",
              background: "var(--mui-palette-secondary-secondary-main)",
              padding: "0",
              boxShadow: "none",
            },
          },
        },
      },
    },
  },
}
