export const typography = {
  h1: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 600,
    fontSize: "96px",
    lineHeight: "117%",
    fontStyle: "semibold",
    letterSpacing: "-0.5px",
  },
  h2: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 600,
    fontSize: "60px",
    lineHeight: "120%",
    fontStyle: "semibold",
    letterSpacing: "-0.5px",
  },
  h3: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 600,
    fontSize: "48px",
    lineHeight: "117%",
    fontStyle: "semibold",
    letterSpacing: "0px",
  },
  h4: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 500,
    fontSize: "32px",
    lineHeight: "124%",
    fontStyle: "medium",
    letterSpacing: "0px",
  },
  h5: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 500,
    fontSize: "24px",
    lineHeight: "133%",
    fontStyle: "medium",
    letterSpacing: "0px",
  },
  h6: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 500,
    fontSize: "20px",
    lineHeight: "160%",
    fontStyle: "medium",
    letterSpacing: "0px",
  },
  body1: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "150%",
    fontStyle: "regular",
    letterSpacing: "0px",
  },
  body2: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 400,
    fontSize: "14px",
    lineHeight: "143%",
    letterSpacing: "0px",
  },
  subtitle1: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 400,
    fontSize: "16px",
    lineHeight: "175%",
    letterSpacing: "0px",
  },
  subtitle2: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "157%",
    fontStyle: "semibold",
    letterSpacing: "0px",
  },
  overline: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "100%",
    letterSpacing: "1px",
    textTransform: "uppercase",
  },
  caption: {
    fontFamily: "Inter, Helvetica, Arial, sans-serif",
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "100%",
    letterSpacing: "0px",
  },
}
