export const footerLandingDefaults = {
  stayUpdatedWith: "Stay updated with",
  decentraland: "Decentraland",
  resources: "Resources",
  marketplace: "Marketplace",
  creatorHub: "Creator Hub",
  docs: "Docs",
  events: "Events",
  blog: "Blog",
  connect: "Connect",
  support: "Support",
  email: "Email",
  dao: "DAO",
  faq: "FAQ",
} as const
