name: Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/
          cache: "npm"

      - name: installing
        run: npm install

      # review this step
      #- name: creating @MUI component and build storybook
      #  run: npm run build-storybook

      - name: linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
