name: Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm install

      # review this step
      #- name: creating @MUI component and build storybook
      #  run: npm run build-storybook

      - name: test
        run: npm test

      - name: validate
        run: npm run lint:check

      - name: linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
