name: Pull Request

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize

jobs:
  release:
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm install

      - name: test
        run: npm test

      - name: validate
        run: npm run lint:check

      - name: linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: true
          prettier_extensions: ts,tsx,js,jsx,json,md,mdx,css
          continue_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: publish packages
        uses: decentraland/oddish-action@master
        id: publish_package
        with:
          registry-url: "https://registry.npmjs.org"
          access: public
          ## use action runId instead of current date to generate snapshot numbers
          deterministic-snapshot: true

          ## publish every package to s3
          s3-bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          s3-bucket-key-prefix: "@dcl/${{ github.event.repository.name }}/branch/${{ github.head_ref }}"
          s3-bucket-region: ${{ secrets.SDK_TEAM_AWS_REGION }}

          ## inform gitlab after publishing to proceed with CDN propagation
          gitlab-token: ${{ secrets.GITLAB_TOKEN }}
          gitlab-pipeline-url: ${{ secrets.GITLAB_URL }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_DEFAULT_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}
